[workspace]
resolver = "2"
members = ["core", "glane", "widgets"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "GUI layout library"
repository = "https://github.com/btanno/glane"

[profile.release-debug]
inherits = "release"
debug = 1