[workspace]
resolver = "2"
members = ["core", "glane", "widgets"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "GUI library"
repository = "https://github.com/btanno/glane"

