[package]
name = "glane-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
gdueiv = { version = "0.1.3", features = ["serde"] }
num = "0.4.1"
rustybuzz = "0.12.1"
sys-locale = "0.3.1"
