[package]
name = "glane-widgets"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
glane-core = { path = "../core" }
num = "0.4.1"
rustybuzz = "0.20"
unicode-normalization = "0.1"
