[package]
name = "glane-widgets"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
glane-core = { path = "../core" }
rustybuzz = "0.12.1"
unicode-normalization = "0.1.22"
