[package]
name = "glane-widgets"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
glane-core = { path = "../core" }
unicode-normalization = "0.1"
rustybuzz.workspace = true
num.workspace = true
